service: nestjs-serverless-poc
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-deployment-bucket
  # *** offline plugins ***
  - serverless-offline-sqs
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  region: eu-west-1
  lambdaHashingVersion: '20201221'
  profile: ${env:AWS_PROFILE}
  memorySize: 1024
  timeout: 20
  versionFunctions: false
  ecr:
    images:
      appimage:
        path: ./
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:SUBNET_PRIVATE_A_ID}
      - ${env:SUBNET_PRIVATE_B_ID}
      - ${env:SUBNET_DATABASE_A_ID}
      - ${env:SUBNET_DATABASE_B_ID}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "*"
          Resource: "*"
  deploymentBucket:
    name: ${self:service}-sls-state-${sls:stage}
  environment:
      STAGE: ${sls:stage}
      NODE_ENV: ${env:NODE_ENV}
      COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
      COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
      COGNITO_REGION: ${env:COGNITO_REGION}
      DEFAULT_FROM_MAIL: ${env:DEFAULT_FROM_MAIL}
      DESTINATION_EMAIL_TEST: ${env:DESTINATION_EMAIL_TEST}
      POSTGRES_HOST: ${env:POSTGRES_HOST}
      POSTGRES_PORT: ${env:POSTGRES_PORT}
      POSTGRES_DATABASE: ${env:POSTGRES_DATABASE}
      POSTGRES_USER: ${env:POSTGRES_USER}
      POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}

      #SQS
      EMQ_ENDPOINT: ${env:EMQ_ENDPOINT}
      #SQS_EMAIL_QUEUE_URL:  ${env:SQS_LOCAL_EMAIL_QUEUE_NAME, !Ref EmailQueue}

custom:

  deploymentBucket:
    accelerate: true
    blockPublicAccess: true
  # *** offline plugins config ***
  serverless-offline:
    noPrependStageInUrl: true
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: "2012-11-05"
    endpoint: http://0.0.0.0:9324
    region: ${self:provider.region}
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false


functions:
  http:
    handler: dist/src/main-http-lambda.handler
#    image:
#      name: appimage
#      command:
#        - dist/src/main-http-lambda.handler
    events:
      - httpApi:
          method: '*'
          path: /
      - httpApi:
          method: '*'
          path: /{proxy+}
  sqs:
    handler: dist/src/main-sqs-lambda.handler
#    image:
#      name: appimage
#      command:
#        - dist/src/main-sqs-lambda.handler
    events:
      - sqs:
          batchSize: 10
          arn:
            Fn::GetAtt: [ EmailQueue, Arn ]
resources:
  Resources:
    EmailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-EmailQueue-${sls:stage}
