service: nestjs-serverless-poc-table
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  region: ${opt:region, 'eu-west-1'}
  profile: ${env:AWS_PROFILE}
  stackTags:
    STACK_NAME: ${self:service}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET_PREFIX}-${sls:stage}
  logRetentionInDays: 14

plugins:
  - serverless-deployment-bucket

custom:
  tableName: ${self:service}-${sls:stage}
resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: pk1
            AttributeType: S
          - AttributeName: sk1
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: invertedIndex
            KeySchema:
              - AttributeName: sk
                KeyType: HASH
              - AttributeName: pk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: gsi_1
            KeySchema:
              - AttributeName: pk1
                KeyType: HASH
              - AttributeName: sk1
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

  Outputs:
    TableName:
      Value: !Ref Table
      Export:
        Name: ${self:custom.tableName}
