Resources:
  ApiRecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    DeletionPolicy: Delete
    DependsOn:
      - ApiCloudFrontDistribution
    Properties:
      HostedZoneName: ${self:custom.config.rootDomainName}.
      RecordSets:
        - Name: ${self:custom.config.apiDomainName}
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: { 'Fn::GetAtt': [ApiCloudFrontDistribution, DomainName] }
