Resources:
  StaticRecord:
    Type: AWS::Route53::RecordSetGroup
    DeletionPolicy: Delete
    DependsOn:
      - StaticCloudFrontDistribution
    Properties:
      HostedZoneName: ${self:custom.domains.root}.
      RecordSets:
        - Name: ${self:custom.domains.static}
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName:
              { 'Fn::GetAtt': [StaticCloudFrontDistribution, DomainName] }
