environment:
  AWS_ACCOUNT_ID: ${aws:accountId}
  STAGE: ${sls:stage}
  NODE_ENV: ${env:NODE_ENV}
  IS_OFFLINE: ${self:custom.config.isOffline}
  COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
  COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
  COGNITO_REGION: ${env:COGNITO_REGION}
  DEFAULT_FROM_MAIL: ${env:DEFAULT_FROM_MAIL}
  DESTINATION_EMAIL_TEST: ${env:DESTINATION_EMAIL_TEST}
  POSTGRES_HOST: ${env:POSTGRES_HOST}
  POSTGRES_PORT: ${env:POSTGRES_PORT}
  POSTGRES_DATABASE: ${env:POSTGRES_DATABASE}
  POSTGRES_USER: ${env:POSTGRES_USER}
  POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
  #SQS
  EMQ_ENDPOINT: ${env:EMQ_ENDPOINT, null}
  EMAIL_QUEUE_NAME: '${self:custom.config.emailQueueName}'
