environment:
  AWS_ACCOUNT_ID: ${aws:accountId}
  STAGE: ${sls:stage}
  NODE_ENV: ${env:NODE_ENV}

  # DATABASE
  POSTGRES_HOST: ${env:POSTGRES_HOST}
  POSTGRES_PORT: ${env:POSTGRES_PORT}
  POSTGRES_DATABASE: ${env:POSTGRES_DATABASE}
  POSTGRES_USER: ${env:POSTGRES_USER}
  POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}

  # COGNITO
  IS_OFFLINE: ${self:custom.config.isOffline}
  COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
  COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
  COGNITO_REGION: ${env:COGNITO_REGION}

  # SES
  DEFAULT_SENDER_ADDRESS: ${env:DEFAULT_SENDER_ADDRESS}
  TEST_RECIPIENT_ADDRESS: ${env:TEST_RECIPIENT_ADDRESS}

  #SQS
  LOCAL_BROKER_ENDPOINT: ${env:LOCAL_BROKER_ENDPOINT, null}
  EMAIL_QUEUE_NAME: ${self:custom.config.emailQueueName}
