environment:
  AWS_ACCOUNT_ID: ${aws:accountId}
  STAGE: ${sls:stage}
  NODE_ENV: ${self:custom.nodeEnv}
  IS_OFFLINE: ${self:custom.offline.enabled}

  # S3
  S3_BUCKET_NAME: ${self:custom.s3.bucketName}

  # DATABASE
  DATABASE_HOST: ${self:custom.database.host}
  DATABASE_PORT: ${self:custom.database.port}
  DATABASE_NAME: ${self:custom.database.name}
  DATABASE_SECRET_ARN: ${self:custom.database.secretArn}

  # COGNITO
  COGNITO_USER_POOL_ID: ${self:custom.cognito.userPoolId}
  COGNITO_CLIENT_ID: ${self:custom.cognito.clientId}

  # SES
  DEFAULT_SENDER_ADDRESS: ${env:DEFAULT_SENDER_ADDRESS}
  TEST_RECIPIENT_ADDRESS: ${env:TEST_RECIPIENT_ADDRESS}

  #SQS
  LOCAL_BROKER_ENDPOINT: ${env:LOCAL_BROKER_ENDPOINT, null}
  EMAIL_QUEUE_NAME: ${self:custom.sqs.emailQueueName}

  ENABLE_SWAGGER: ${env:ENABLE_SWAGGER, false}
  ENABLE_GRAPHQL_INTROSPECTION: ${env:ENABLE_GRAPHQL_INTROSPECTION, false}
  ENABLE_GRAPHQL_PLAYGROUND: ${env:ENABLE_GRAPHQL_PLAYGROUND, false}
