environment:
  AWS_ACCOUNT_ID: ${aws:accountId}
  STAGE: ${sls:stage}
  NODE_ENV: ${env:NODE_ENV}

  # S3
  S3_BUCKET_NAME: ${self:custom.s3BucketName}

  # DATABASE
  DATABASE_HOST: ${env:DATABASE_HOST}
  DATABASE_PORT: ${env:DATABASE_PORT}
  DATABASE_NAME: ${env:DATABASE_NAME}
  DATABASE_SECRET_ARN: ${env:DATABASE_SECRET_ARN}

  # COGNITO
  IS_OFFLINE: ${self:custom.isOffline}
  COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
  COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
  COGNITO_REGION: ${env:COGNITO_REGION}

  # SES
  DEFAULT_SENDER_ADDRESS: ${env:DEFAULT_SENDER_ADDRESS}
  TEST_RECIPIENT_ADDRESS: ${env:TEST_RECIPIENT_ADDRESS}

  #SQS
  LOCAL_BROKER_ENDPOINT: ${env:LOCAL_BROKER_ENDPOINT, null}
  EMAIL_QUEUE_NAME: ${self:custom.emailQueueName}

  ENABLE_SWAGGER: ${env:ENABLE_SWAGGER, false}
  ENABLE_GRAPHQL_INTROSPECTION: ${env:ENABLE_GRAPHQL_INTROSPECTION, false}
  ENABLE_GRAPHQL_PLAYGROUND: ${env:ENABLE_GRAPHQL_PLAYGROUND, false}
