Resources:
  ApiCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DeletionPolicy: Delete
    DependsOn:
      - ApiLambdaFunctionUrl
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        HttpVersion: http2
        Comment: Api distribution ${sls:stage}
        Origins:
          - Id: ApiLambdaFunction
            DomainName:
              !Select [
                2,
                !Split ['/', !GetAtt ApiLambdaFunctionUrl.FunctionUrl],
              ]
            OriginPath: ''
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [TLSv1, TLSv1.1, TLSv1.2]
        DefaultCacheBehavior:
          TargetOriginId: ApiLambdaFunction
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          MinTTL: 0
          DefaultTTL: 0
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - HEAD
            - OPTIONS
            - GET
          ForwardedValues:
            QueryString: false
            Headers:
              - Accept
              - x-api-key
              - Authorization
            Cookies:
              Forward: none
        Aliases:
          - ${self:custom.apiDomainName}
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2019
          AcmCertificateArn: ${self:custom.certificateNVirginaArn}
