Resources:
  ApisCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DeletionPolicy: Delete
    DependsOn:
      - OrgPublicApiLambdaFunctionUrl
      - OrgManagementApiLambdaFunctionUrl
      - InternalApiLambdaFunctionUrl
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        HttpVersion: http2
        Comment: ${self:service}-${sls:stage} APIs distribution
        Origins:
          # Org Public API Lambda Function Origin
          - Id: OrgPublicApiLambdaFunction
            DomainName:
              !Select [
                2,
                !Split ['/', !GetAtt OrgPublicApiLambdaFunctionUrl.FunctionUrl],
              ]
            OriginPath: ''
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [TLSv1, TLSv1.1, TLSv1.2]
          # Org Management API Lambda Function Origin
          - Id: OrgManagementApiLambdaFunction
            DomainName:
              !Select [
                2,
                !Split [
                  '/',
                  !GetAtt OrgManagementApiLambdaFunctionUrl.FunctionUrl,
                ],
              ]
            OriginPath: ''
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [TLSv1, TLSv1.1, TLSv1.2]
          # Org Management API Lambda Function Origin
          - Id: InternalApiLambdaFunction
            DomainName:
              !Select [
                2,
                !Split ['/', !GetAtt InternalApiLambdaFunctionUrl.FunctionUrl],
              ]
            OriginPath: ''
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [TLSv1, TLSv1.1, TLSv1.2]
        DefaultCacheBehavior:
          # ======================== Default CacheBehavior  ========================
          TargetOriginId: OrgPublicApiLambdaFunction
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          MinTTL: 0
          DefaultTTL: 0
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - HEAD
            - OPTIONS
            - GET
          ForwardedValues:
            QueryString: false
            Headers:
              - Accept
              - x-api-key
              - Authorization
            Cookies:
              Forward: none
        CacheBehaviors:
          # ======================== Org Public API CacheBehavior  ========================
          - PathPattern: /${self:custom.appsConfig.orgPublic.prefix}/*
            TargetOriginId: OrgPublicApiLambdaFunction
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            MinTTL: 0
            DefaultTTL: 0
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - OPTIONS
              - GET
            ForwardedValues:
              QueryString: false
              Headers:
                - Accept
                - x-api-key
                - Authorization
              Cookies:
                Forward: none
          # ======================== Org Management API CacheBehavior  ========================
          - PathPattern: /${self:custom.appsConfig.orgManagement.prefix}/*
            TargetOriginId: InternalApiLambdaFunction
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            MinTTL: 0
            DefaultTTL: 0
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - OPTIONS
              - GET
            ForwardedValues:
              QueryString: false
              Headers:
                - Accept
                - x-api-key
                - Authorization
              Cookies:
                Forward: none
          # ======================== Internal API CacheBehavior  ========================
          - PathPattern: /${self:custom.appsConfig.internal.prefix}/*
            TargetOriginId: OrgManagementApiLambdaFunction
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            MinTTL: 0
            DefaultTTL: 0
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - HEAD
              - OPTIONS
              - GET
            ForwardedValues:
              QueryString: false
              Headers:
                - Accept
                - x-api-key
                - Authorization
              Cookies:
                Forward: none
        Aliases:
          - ${self:custom.apiDomainName}
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2019
          AcmCertificateArn: ${self:custom.certificateNVirginaArn}
